### ISSUE TITLE
Navigarot lua 

### ISSUE THREAD

**Issue by borek24** [PyxFramework/PyxBDO#11]
if not selfPlayer.IsBattleMode then
            selfPlayer:DoAction("JUMP_F_A")
            else
            selfPlayer:DoAction("BT_JUMP_F_A")
            end

if not selfPlayer.IsBattleMode then
				selfPlayer:DoAction("RUN_SPRINT_FAST_ST")
			else
				selfPlayer:DoAction("BT_RUN_SPRINT")
			end

**Comment by Triplany** [comment]
fixed in newest
